### ISSUE TITLE
Взаимодействие между фасадом и другими микросервисами.

### ISSUE THREAD

**Issue by ted7007** [FizzyShow/markershtern#16]
Проблема:  
Сейчас у нас возникают сомнения о взаимодействии между фасадом и другими микросервисами.  
  
Возникают следующие варианты решения:  
 - Мы используем gRPC для связи с Facade, а Kafka для общения между микросевисами?  
 - gRPC мы используем для получения состояния, а Kafka используется, когда нужно что-то создать, изменить(изменить состояние)?

**Comment by ted7007** [comment]
Получили ответ от куратора, что все же используем первый вариант решения  
Мы используем gRPC для связи client-facade-service, а Kafka для общения между микросевисами.

**Comment by ted7007** [comment]
Насколько я понял взаимодействие фасада с сервисами по grpc необходимо для немедленного ответа, чтобы синхронно проходиться по сервисам

**Comment by stictt** [comment]
Выделение передачи данных за Кафку вышло из следующей проблемы. 
"У нас есть условный бекенд, у бекенда сотни сессий. Все они запрашивают товар на userId и все они подписаны на один топик. В топике получается свалка с сообщениями для всех. Чтобы найти нужное сообщение, нужно разобрать их все. Каждый должен обработать каждое сообщение. Т.е мы не можем гарантировать адресную доставку, в структуре продюсер>топик>консюмер"

**Comment by stictt** [comment]
У меня есть три теоретические варианты решения этой проблемы. 

> Использовать подключение точка точка для не структурированных сообщений которые являются получениями состояния. 

> Второе. Использовать headers и key в сообщениях, которые помогут разобрать кому это сообщение.
Headers могут быть использованы для предпросмотра содержимого сообщения, до его десериализации, смотрим header и думаем нужно ли нам десериализовать сообщение, так мы в теории экономим часть ресурсов во время чтения. 
Key можно прочитать только после десериализации. 
Оба этих инструмента, в теории могут помочь с роутингом сообщений в самой системе kafka и балансировать нагрузку. Но с этим надо ещё разобраться. 

> Использование stream kafka, тут много сложностей. Одна из них это то, что темы для стримов должны быть созданы до старта приложения. Какие варианты фильтрации нам могут дать не сильно ясно. Так же стандартный провайдер для C# не поддерживает stream, нужно смотреть сторонние библиотеки. 

> Есть ksql механизм для помощи создания стримов и запросам. Предположительно, для работы требует отдельный поднятый микросервис который подключается к kafka

**Comment by stictt** [comment]
На текущем этапе я думаю мы можем использовать только headers с блокировкой десериализации. На больших массивных сообщения которые имеют сложную структуру с массивами и вложенными классами. Я думаю мы выйграем по производительности.

**Comment by kazurus** [comment]
Consumer ровно один на partition. Может быть один consumer на два partition, но не может быть два consumer на одну partition в рамках одной consumer group. События можно [привязывать к определённой partition](https://silverback-messaging.net/concepts/broker/kafka/kafka-partitioning.html?tabs=destination-partition-fluent%2Cenricher-fluent%2Cconcurrency-fluent%2Cassignment-fluent)

**Comment by kazurus** [comment]
https://developer.confluent.io/learn-kafka/apache-kafka/partitions/

**Comment by stictt** [comment]
Очень помогло. Разобрался. 
в kafka\config ищем server.properties 
в нем num.partitions, отвечает за кол возможных partition , у меня стоял по дефолту в 1. 
![image](https://user-images.githubusercontent.com/19176407/181933729-906bdb57-157a-4a8a-871b-3a2d8b07c336.png)
Во время создания топика, необходимо отслеживать максимально доступное кол partition, по дефолту стоял так же в 1. 
Для консюмера. 
чтобы указать раздел чтения. используем следующую конструкцию 
![image](https://user-images.githubusercontent.com/19176407/181933778-0f957d02-8737-4a42-a97a-ad39a597b3eb.png)
Создаем TopicPartition и в нем указывает топик, и создаем структуру с номером раздела. 
И передаем это в консюмер. При чтении, он будет пользоваться этими данными. Отдельно указывать топик, не нужно. 
Для Продюсера 
![image](https://user-images.githubusercontent.com/19176407/181933859-6cb4df6b-a6ba-4a6a-b453-14c7e53e7a78.png)
Во время отправки сообщения продюсеру скармливаем TopicPartition вместо строки топика. 
Сообщения будут разделяться согласно номеру. 
так же мы получаем нечто вроде хеш карты. 
Думаю Будет не плохо совместить это с проверкой Headers, тогда ни каких проблем с производительностью не должно быть. 
Так же Есть вероятность что Headers будет переопределен самой kafka нужно чекать, там это связанно с какой то системой движения сообщений.

**Comment by stictt** [comment]
На совещании команды отказались от варианта общения точка точка. 
Все сообщения, в том числе от фасада и к фасаду, будут идти через Kafka. 
Предполагается следующее взаимодействие. 
Для запросов данных, мы формируем два топика. Один топик для сообщения ответа, откуда читать будем. Другой топик для сообщения, чтобы нам сформировали данные. 

```mermaid
stateDiagram-v2
    Фасад  --> ТопикЗапроса:head = token(21) \n key = 3\n message = idProduct
    ТопикЗапроса --> Партиция: head = token(21) \n key = 3\n message = idProduct
    Партиция --> МикросервисТоваров: head = token(21) \n key = 3\n message = idProduct
    МикросервисТоваров --> ТопикОтвета: head = token(21) \n key = 3\n message = listproduct 
    ТопикОтвета --> Партиция1
    ТопикОтвета --> Партиция2   
    ТопикОтвета --> Партиция3 : head = token(21) \n key = 3\n message = listproduct 
    Партиция3 -->  Фасад : head = token(21) \n key = 3\n message = listproduct      
```
Запрос приходит в один топик, в одну партицию (опционально), откуда на конкурентной основе, сообщения будут разбирать консюмеры. 

Сообщение состоит из header key message
header будет хранить в себе следующую конструкцию (key = токен, value = null)
где токен будет уникальная случайная строка. 
header Будет отвечать за указатель, кому это сообщение адресовано. Сервисы будет ждать ответы только с header  и токеном который они сами сгенерировали для себя. 
key будет отвечать за то, в какую партицию будет доставлен ответ, на эту партицию и будем формировать консюмер. 
message сообщение необходимое для работы, например там могут быть idUser и хотим по нему получить список всех его товаров. А ответное сообщение, будет состоять из товаров по этому IdUser. 

Можно предположить стандартное кол партиций например 5. Для топика который будет содержать ответ.

**Comment by kazurus** [comment]
А почему решили отказаться от общения напрямую между фасадом и сервисом?

**Comment by paradoxubivaet** [comment]
Потому что проблема, из-за которой мы решили перейти к общению напрямую, решилась.  

Сергей - ""У нас есть условный бекенд, у бекенда сотни сессий. Все они запрашивают товар на userId и все они подписаны на один топик. В топике получается свалка с сообщениями для всех. Чтобы найти нужное сообщение, нужно разобрать их все. Каждый должен обработать каждое сообщение. Т.е мы не можем гарантировать адресную доставку, в структуре продюсер>топик>консюмер""

**Comment by stictt** [comment]
Общение точка точка, это костыль, который основан на том, что мы не знаем другого решения. У него есть проблемы. Проблемы с масштабированием. 
kafka и использование ее как message bus, приближено к реальной проблеме, с которой можем столкнуться в работе. И имеет преимущества. 
мы можем маштабировать так, что у нас будет не 1 микросервис с товарами отвечать на запросы, а допустим 10. Когда не будет хватать мощностей системе. И мы абстрагируемся от проблемы прямого обращения. У нас могут микросервисы товаров отвалиться, и при этом, система будет работать.

**Comment by ted7007** [comment]
На встрече решили вопрос.
Реализация request-response общения через кафку является не рациональным решением, когда есть альтернатива в виде grpc.
